# Generated by Django 5.2 on 2025-07-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_app', '0002_remove_quiz_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='mentor',
            new_name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='video',
            name='domain',
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(),
        ),
    ]
