# Generated by Django 5.2 on 2025-07-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_app', '0004_quizanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('basic', 'Basique'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé')], default='basic', max_length=20, verbose_name='Niveau de difficulté'),
        ),
    ]
