# Generated by Django 5.2 on 2025-07-20 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_app', '0008_pdfdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfdocument',
            name='uploaded_by',
        ),
        migrations.DeleteModel(
            name='MentorPDF',
        ),
        migrations.DeleteModel(
            name='PDFDocument',
        ),
    ]
